import {
  CompilationUnit,
  ImportDeclaration,
  ClassDeclaration,
  InterfaceDeclaration,
  FieldDeclaration,
  MethodDeclaration,
  Parameter,
  BlockStatement,
  VariableDeclaration,
  IfStatement,
  ForStatement,
  WhileStatement,
  DoWhileStatement,
  ReturnStatement,
  ExpressionStatement,
  AssignmentExpression,
  BinaryExpression,
  UnaryExpression,
  CallExpression,
  MemberExpression,
  NewExpression,
  Identifier,
  Literal,
  ThisExpression,
  SuperExpression,
  ArrayLiteral,
  TryCatchStatement,
  ThrowStatement,
  BreakStatement,
  ContinueStatement,
  Statement,
  Expression,
  TypeReference,
} from '../parser/ast/AST';

const TYPE_MAP: Record<string, string> = {
  int: 'Number',
  long: 'Number',
  float: 'Number',
  double: 'Number',
  boolean: 'Boolean',
  char: 'String',
  byte: 'Number',
  short: 'Number',
  String: 'String',
  void: 'void',
};

export class CodeGenerator {
  private output: string[] = [];
  private indentLevel: number = 0;
  private privateFields: Map<string, string> = new Map();

  public generate(ast: CompilationUnit): string {
    this.output = [];
    this.indentLevel = 0;
    this.privateFields.clear();

    this.emitLine('// Generated by JaJS Compiler');
    this.emitLine('// DO NOT EDIT THIS FILE');
    this.emitLine('');

    for (const imp of ast.imports) {
      this.generateImport(imp);
    }

    if (ast.imports.length > 0) {
      this.emitLine('');
    }

    for (const decl of ast.declarations) {
      if (decl.type === 'ClassDeclaration') {
        this.generateClass(decl);
        this.emitLine('');
      }
    }

    return this.output.join('\n');
  }

  private generateImport(node: ImportDeclaration): void {
    const parts = node.path.split('.');
    const last = parts[parts.length - 1];
    if (last === '*') {
      this.emitLine(`import * from '${node.path}';`);
    } else {
      this.emitLine(`import ${last} from '${node.path}';`);
    }
  }

  private generateClass(node: ClassDeclaration): void {
    const isPrivate = node.modifiers.includes('private');
    const exportKeyword = node.modifiers.includes('public') ? 'export ' : isPrivate ? '' : 'export ';

    let extendsClause = '';
    if (node.superClass) {
      extendsClause = ` extends ${node.superClass.name}`;
    }

    this.emitLine(`${exportKeyword}class ${node.name}${extendsClause} {`);
    this.indentLevel++;

    this.privateFields.clear();
    for (const member of node.members) {
      if (member.type === 'FieldDeclaration' && member.modifiers.includes('private')) {
        this.privateFields.set(member.name, `#${member.name}`);
      }
    }

    const hasConstructor = node.members.some(
      (m) => m.type === 'MethodDeclaration' && m.name === node.name,
    );

    if (!hasConstructor) {
      this.emitLine(`constructor() {`);
      this.indentLevel++;
      for (const member of node.members) {
        if (member.type === 'FieldDeclaration' && member.initializer) {
          const fieldName = this.getFieldName(member.name, member.modifiers);
          this.emitLine(`this.${fieldName} = ${this.generateExpression(member.initializer)};`);
        }
      }
      this.indentLevel--;
      this.emitLine('}');
      this.emitLine('');
    }

    let first = true;
    for (const member of node.members) {
      if (!first) this.emitLine('');
      first = false;

      if (member.type === 'FieldDeclaration') {
        this.generateField(member);
      } else if (member.type === 'MethodDeclaration') {
        this.generateMethod(member, node.name);
      }
    }

    this.indentLevel--;
    this.emitLine('}');
  }

  private getFieldName(name: string, modifiers: string[]): string {
    if (modifiers.includes('private')) {
      return this.privateFields.get(name) || `#${name}`;
    }
    return name;
  }

  private generateField(node: FieldDeclaration): void {
    const fieldName = this.getFieldName(node.name, node.modifiers);
    const staticKeyword = node.modifiers.includes('static') ? 'static ' : '';

    if (!node.modifiers.includes('private') && node.initializer) {
      this.emitLine(`${staticKeyword}${fieldName} = ${this.generateExpression(node.initializer)};`);
    } else if (!node.modifiers.includes('private')) {
      this.emitLine(`${staticKeyword}${fieldName};`);
    }
  }

  private generateMethod(node: MethodDeclaration, className: string): void {
    if (node.isAbstract) return;

    const isConstructor = node.name === className;
    const staticKeyword = node.modifiers.includes('static') ? 'static ' : '';

    if (isConstructor) {
      this.emitLine(`constructor(${this.generateParameters(node.parameters)}) {`);
      this.indentLevel++;
      for (const member of (node as any).parent?.members || []) {
        if (member.type === 'FieldDeclaration' && member.initializer && !node.parameters.some((p) => p.name === member.name)) {
          const fieldName = this.getFieldName(member.name, member.modifiers);
          this.emitLine(`this.${fieldName} = ${this.generateExpression(member.initializer)};`);
        }
      }
      if (node.body) {
        const stmts = this.generateBlockStatements(node.body);
        if (stmts.trim()) {
          this.emitRaw(stmts);
        }
      }
      this.indentLevel--;
      this.emitLine('}');
      return;
    }

    const methodName = node.modifiers.includes('private') ? `#${node.name}` : node.name;

    this.emitLine(`${staticKeyword}${methodName}(${this.generateParameters(node.parameters)}) {`);
    this.indentLevel++;
    if (node.body) {
      this.emitRaw(this.generateBlockStatements(node.body));
    }
    this.indentLevel--;
    this.emitLine('}');
  }

  private generateParameters(params: Parameter[]): string {
    return params.map((p) => p.name).join(', ');
  }

  private generateBlockStatements(node: BlockStatement): string {
    const result: string[] = [];
    for (const stmt of node.statements) {
      result.push(this.generateStatement(stmt));
    }
    return result.join('');
  }

  private generateStatement(node: Statement): string {
    switch (node.type) {
      case 'BlockStatement':
        return this.generateBlock(node);
      case 'VariableDeclaration':
        return this.generateVariableDeclaration(node);
      case 'IfStatement':
        return this.generateIfStatement(node);
      case 'ForStatement':
        return this.generateForStatement(node);
      case 'WhileStatement':
        return this.generateWhileStatement(node);
      case 'DoWhileStatement':
        return this.generateDoWhileStatement(node);
      case 'ReturnStatement':
        return this.generateReturnStatement(node);
      case 'ExpressionStatement':
        return this.generateExpressionStatement(node);
      case 'TryCatchStatement':
        return this.generateTryCatchStatement(node);
      case 'ThrowStatement':
        return this.generateThrowStatement(node);
      case 'BreakStatement':
        return this.emitLineStr('break;');
      case 'ContinueStatement':
        return this.emitLineStr('continue;');
    }
  }

  private generateBlock(node: BlockStatement): string {
    let result = this.emitLineStr('{');
    this.indentLevel++;
    result += this.generateBlockStatements(node);
    this.indentLevel--;
    result += this.emitLineStr('}');
    return result;
  }

  private generateVariableDeclaration(node: VariableDeclaration): string {
    let result = '';
    if (node.initializer) {
      result += this.emitLineStr(`let ${node.name} = ${this.generateExpression(node.initializer)};`);
    } else {
      result += this.emitLineStr(`let ${node.name};`);
    }
    return result;
  }

  private generateIfStatement(node: IfStatement): string {
    let result = this.emitLineStr(`if (${this.generateExpression(node.condition)}) {`);
    this.indentLevel++;
    result += this.generateStatement(node.consequent);
    this.indentLevel--;
    result = result.slice(0, -1);
    if (node.alternate) {
      result += this.emitLineStr('} else {');
      this.indentLevel++;
      result += this.generateStatement(node.alternate);
      this.indentLevel--;
      result = result.slice(0, -1);
      result += this.emitLineStr('}');
    } else {
      result += this.emitLineStr('}');
    }
    return result;
  }

  private generateForStatement(node: ForStatement): string {
    const parts: string[] = [];
    if (node.init) {
      if (node.init.type === 'VariableDeclaration') {
        parts.push(`let ${node.init.name}${node.init.initializer ? ' = ' + this.generateExpression(node.init.initializer) : ''}`);
      } else {
        parts.push(this.generateExpression(node.init));
      }
    } else {
      parts.push('');
    }
    parts.push(node.condition ? this.generateExpression(node.condition) : '');
    parts.push(node.update ? this.generateExpression(node.update) : '');

    let result = this.emitLineStr(`for (${parts.join('; ')}) {`);
    this.indentLevel++;
    result += this.generateStatement(node.body);
    this.indentLevel--;
    result = result.slice(0, -1);
    result += this.emitLineStr('}');
    return result;
  }

  private generateWhileStatement(node: WhileStatement): string {
    let result = this.emitLineStr(`while (${this.generateExpression(node.condition)}) {`);
    this.indentLevel++;
    result += this.generateStatement(node.body);
    this.indentLevel--;
    result = result.slice(0, -1);
    result += this.emitLineStr('}');
    return result;
  }

  private generateDoWhileStatement(node: DoWhileStatement): string {
    let result = this.emitLineStr('do {');
    this.indentLevel++;
    result += this.generateStatement(node.body);
    this.indentLevel--;
    result = result.slice(0, -1);
    result += this.emitLineStr(`} while (${this.generateExpression(node.condition)});`);
    return result;
  }

  private generateReturnStatement(node: ReturnStatement): string {
    if (node.argument) {
      return this.emitLineStr(`return ${this.generateExpression(node.argument)};`);
    }
    return this.emitLineStr('return;');
  }

  private generateExpressionStatement(node: ExpressionStatement): string {
    return this.emitLineStr(`${this.generateExpression(node.expression)};`);
  }

  private generateTryCatchStatement(node: TryCatchStatement): string {
    let result = this.emitLineStr('try {');
    this.indentLevel++;
    result += this.generateBlockStatements(node.tryBlock);
    this.indentLevel--;
    result = result.slice(0, -1);

    if (node.catchBlock && node.catchParam) {
      result += this.emitLineStr(`} catch (${node.catchParam.name}) {`);
      this.indentLevel++;
      result += this.generateBlockStatements(node.catchBlock);
      this.indentLevel--;
      result = result.slice(0, -1);
    }

    if (node.finallyBlock) {
      result += this.emitLineStr('} finally {');
      this.indentLevel++;
      result += this.generateBlockStatements(node.finallyBlock);
      this.indentLevel--;
      result = result.slice(0, -1);
    }

    result += this.emitLineStr('}');
    return result;
  }

  private generateThrowStatement(node: ThrowStatement): string {
    return this.emitLineStr(`throw ${this.generateExpression(node.argument)};`);
  }

  private generateExpression(node: Expression): string {
    switch (node.type) {
      case 'AssignmentExpression':
        return this.generateAssignmentExpression(node);
      case 'BinaryExpression':
        return this.generateBinaryExpression(node);
      case 'UnaryExpression':
        return this.generateUnaryExpression(node);
      case 'CallExpression':
        return this.generateCallExpression(node);
      case 'MemberExpression':
        return this.generateMemberExpression(node);
      case 'NewExpression':
        return this.generateNewExpression(node);
      case 'Identifier':
        return node.name;
      case 'Literal':
        return this.generateLiteral(node);
      case 'ThisExpression':
        return 'this';
      case 'SuperExpression':
        return 'super';
      case 'ArrayLiteral':
        return this.generateArrayLiteral(node);
    }
  }

  private generateAssignmentExpression(node: AssignmentExpression): string {
    const left = this.generateExpression(node.left);
    const right = this.generateExpression(node.right);
    return `${left} ${node.operator} ${right}`;
  }

  private generateBinaryExpression(node: BinaryExpression): string {
    if (node.operator === '?:') {
      const cond = this.generateExpression(node.left);
      const cons = this.generateExpression((node.right as BinaryExpression).left);
      const alt = this.generateExpression((node.right as BinaryExpression).right);
      return `${cond} ? ${cons} : ${alt}`;
    }
    const left = this.generateExpression(node.left);
    const right = this.generateExpression(node.right);
    return `${left} ${node.operator} ${right}`;
  }

  private generateUnaryExpression(node: UnaryExpression): string {
    const operand = this.generateExpression(node.operand);
    if (node.prefix) {
      return `${node.operator}${operand}`;
    }
    return `${operand}${node.operator}`;
  }

  private generateCallExpression(node: CallExpression): string {
    let callee = this.generateExpression(node.callee);
    const args = node.arguments.map((a) => this.generateExpression(a)).join(', ');

    if (node.callee.type === 'MemberExpression' && node.callee.property.type === 'Identifier') {
      const propName = node.callee.property.name;
      if (propName === 'println') {
        const obj = this.generateExpression(node.callee.object);
        if (obj === 'System.out' || obj === 'console') {
          return `console.log(${args})`;
        }
      }
      if (propName === 'print') {
        const obj = this.generateExpression(node.callee.object);
        if (obj === 'System.out' || obj === 'console') {
          return `console.log(${args})`;
        }
      }
    }

    if (node.callee.type === 'Identifier') {
      if (node.callee.name === 'println') {
        return `console.log(${args})`;
      }
      if (node.callee.name === 'print') {
        return `console.log(${args})`;
      }
    }

    return `${callee}(${args})`;
  }

  private generateMemberExpression(node: MemberExpression): string {
    const object = this.generateExpression(node.object);
    if (node.property.type === 'Identifier') {
      let propName = node.property.name;
      if (object === 'this') {
        propName = this.privateFields.get(propName) || propName;
      }
      if (object === 'System' && propName === 'out') {
        return 'console';
      }
      return `${object}.${propName}`;
    }
    const index = this.generateExpression(node.property);
    return `${object}[${index}]`;
  }

  private generateNewExpression(node: NewExpression): string {
    const args = node.arguments.map((a) => this.generateExpression(a)).join(', ');
    if (node.className.isArray) {
      if (node.arguments.length > 0) {
        return `new Array(${args})`;
      }
      return '[]';
    }
    return `new ${node.className.name}(${args})`;
  }

  private generateLiteral(node: Literal): string {
    switch (node.literalType) {
      case 'string':
        return JSON.stringify(node.value);
      case 'char':
        return JSON.stringify(node.value);
      case 'number':
        return String(node.value);
      case 'boolean':
        return String(node.value);
      case 'null':
        return 'null';
    }
  }

  private generateArrayLiteral(node: ArrayLiteral): string {
    const elements = node.elements.map((e) => this.generateExpression(e)).join(', ');
    return `[${elements}]`;
  }

  private getIndent(): string {
    return '  '.repeat(this.indentLevel);
  }

  private emitLine(line: string): void {
    this.output.push(`${this.getIndent()}${line}`);
  }

  private emitLineStr(line: string): string {
    return `${this.getIndent()}${line}\n`;
  }

  private emitRaw(content: string): void {
    this.output.push(content.trimEnd());
  }
}
